---
- name: Add apt repo key if using official nginx.org repo
  apt_key:
    url: 'http://nginx.org/keys/nginx_signing.key'
  when: nginx_repo is match("deb http://nginx.org/packages/.*")
  tags: [packages, nginx]

- name: Add given nginx repo
  apt_repository:
    repo: "{{ nginx_repo }}"
    state: present
    update_cache: true
  tags: [packages, nginx]
